### ISSUE TITLE
feat: proxy-wasm-rust-host

### ISSUE THREAD

**Issue by darkforest42** [proxy-wasm/proxy-wasm-cpp-host#407]
i'm looking forward to proxy-wasm-rust-host. Are there any plans to develop it?

**Comment by PiotrSikora** [comment]
I had plans to develop it at one point, but the project where it was supposed to be embedded in no longer exists.

At this point, I'm not aware of anyone working on the host implementation in Rust.

Also, this should be asked in [proxy-wasm/spec](https://github.com/proxy-wasm/spec), which acts as a top-level repository for the Proxy-Wasm project, than here, since it's unrelated to C++ Host. Feel free to reopen it there.
